export const LANGUAGES = [
  { group: '🇮🇳 Indian Languages' },
  { code: 'EN', dir: 'ltr', flag: '🇬🇧', label: 'English' },
  { code: 'HI', dir: 'ltr', flag: '🇮🇳', label: 'हिन्दी · Hindi' },
  { code: 'UR', dir: 'rtl', flag: '🇵🇰', label: 'اردو · Urdu' },
  { code: 'BN', dir: 'ltr', flag: '🇧🇩', label: 'বাংলা · Bengali' },
  { code: 'TA', dir: 'ltr', flag: '🇮🇳', label: 'தமிழ் · Tamil' },
  { code: 'TE', dir: 'ltr', flag: '🇮🇳', label: 'తెలుగు · Telugu' },
  { code: 'MR', dir: 'ltr', flag: '🇮🇳', label: 'मराठी · Marathi' },
  { code: 'PA', dir: 'ltr', flag: '🇮🇳', label: 'ਪੰਜਾਬੀ · Punjabi' },
  { code: 'GU', dir: 'ltr', flag: '🇮🇳', label: 'ગુજરાતી · Gujarati' },
  { code: 'KN', dir: 'ltr', flag: '🇮🇳', label: 'ಕನ್ನಡ · Kannada' },
  { code: 'ML', dir: 'ltr', flag: '🇮🇳', label: 'മലയാളം · Malayalam' },
  { code: 'OR', dir: 'ltr', flag: '🇮🇳', label: 'ଓଡ଼ିଆ · Odia' },
  { code: 'AS', dir: 'ltr', flag: '🇮🇳', label: 'অসমীয়া · Assamese' },
  { code: 'NE', dir: 'ltr', flag: '🇳🇵', label: 'नेपाली · Nepali' },
  { code: 'SI', dir: 'ltr', flag: '🇱🇰', label: 'සිංහල · Sinhala' },
  { group: '🌍 World Languages' },
  { code: 'AR', dir: 'rtl', flag: '🇸🇦', label: 'العربية · Arabic' },
  { code: 'ZH', dir: 'ltr', flag: '🇨🇳', label: '中文 · Chinese' },
  { code: 'ES', dir: 'ltr', flag: '🇪🇸', label: 'Español · Spanish' },
  { code: 'FR', dir: 'ltr', flag: '🇫🇷', label: 'Français · French' },
  { code: 'DE', dir: 'ltr', flag: '🇩🇪', label: 'Deutsch · German' },
  { code: 'PT', dir: 'ltr', flag: '🇧🇷', label: 'Português · Portuguese' },
  { code: 'RU', dir: 'ltr', flag: '🇷🇺', label: 'Русский · Russian' },
  { code: 'JA', dir: 'ltr', flag: '🇯🇵', label: '日本語 · Japanese' },
  { code: 'KO', dir: 'ltr', flag: '🇰🇷', label: '한국어 · Korean' },
  { code: 'TR', dir: 'ltr', flag: '🇹🇷', label: 'Türkçe · Turkish' },
  { code: 'ID', dir: 'ltr', flag: '🇮🇩', label: 'Bahasa Indonesia' },
  { code: 'MS', dir: 'ltr', flag: '🇲🇾', label: 'Bahasa Melayu · Malay' },
  { code: 'TH', dir: 'ltr', flag: '🇹🇭', label: 'ภาษาไทย · Thai' },
  { code: 'VI', dir: 'ltr', flag: '🇻🇳', label: 'Tiếng Việt · Vietnamese' },
  { code: 'PL', dir: 'ltr', flag: '🇵🇱', label: 'Polski · Polish' },
  { code: 'IT', dir: 'ltr', flag: '🇮🇹', label: 'Italiano · Italian' },
  { code: 'NL', dir: 'ltr', flag: '🇳🇱', label: 'Nederlands · Dutch' },
  { code: 'UK', dir: 'ltr', flag: '🇺🇦', label: 'Українська · Ukrainian' },
];

export const COUNTRIES = [
  { group: '⭐ Popular' },
  { flag: '🇮🇳', name: 'India',          cur: 'INR', phone: '+91'  },
  { flag: '🇵🇰', name: 'Pakistan',       cur: 'PKR', phone: '+92'  },
  { flag: '🇧🇩', name: 'Bangladesh',     cur: 'BDT', phone: '+880' },
  { flag: '🇦🇪', name: 'UAE',            cur: 'AED', phone: '+971' },
  { flag: '🇸🇦', name: 'Saudi Arabia',   cur: 'SAR', phone: '+966' },
  { flag: '🇺🇸', name: 'United States',  cur: 'USD', phone: '+1'   },
  { flag: '🇬🇧', name: 'United Kingdom', cur: 'GBP', phone: '+44'  },
  { group: '🌍 Asia' },
  { flag: '🇨🇳', name: 'China',          cur: 'CNY', phone: '+86'  },
  { flag: '🇯🇵', name: 'Japan',          cur: 'JPY', phone: '+81'  },
  { flag: '🇰🇷', name: 'South Korea',    cur: 'KRW', phone: '+82'  },
  { flag: '🇮🇩', name: 'Indonesia',      cur: 'IDR', phone: '+62'  },
  { flag: '🇲🇾', name: 'Malaysia',       cur: 'MYR', phone: '+60'  },
  { flag: '🇵🇭', name: 'Philippines',    cur: 'PHP', phone: '+63'  },
  { flag: '🇹🇭', name: 'Thailand',       cur: 'THB', phone: '+66'  },
  { flag: '🇻🇳', name: 'Vietnam',        cur: 'VND', phone: '+84'  },
  { flag: '🇸🇬', name: 'Singapore',      cur: 'SGD', phone: '+65'  },
  { flag: '🇳🇵', name: 'Nepal',          cur: 'NPR', phone: '+977' },
  { flag: '🇱🇰', name: 'Sri Lanka',      cur: 'LKR', phone: '+94'  },
  { group: '🌍 Middle East' },
  { flag: '🇶🇦', name: 'Qatar',          cur: 'QAR', phone: '+974' },
  { flag: '🇰🇼', name: 'Kuwait',         cur: 'KWD', phone: '+965' },
  { flag: '🇧🇭', name: 'Bahrain',        cur: 'BHD', phone: '+973' },
  { flag: '🇴🇲', name: 'Oman',           cur: 'OMR', phone: '+968' },
  { flag: '🇹🇷', name: 'Turkey',         cur: 'TRY', phone: '+90'  },
  { group: '🌍 Europe' },
  { flag: '🇩🇪', name: 'Germany',        cur: 'EUR', phone: '+49'  },
  { flag: '🇫🇷', name: 'France',         cur: 'EUR', phone: '+33'  },
  { flag: '🇮🇹', name: 'Italy',          cur: 'EUR', phone: '+39'  },
  { flag: '🇪🇸', name: 'Spain',          cur: 'EUR', phone: '+34'  },
  { flag: '🇳🇱', name: 'Netherlands',    cur: 'EUR', phone: '+31'  },
  { flag: '🇵🇱', name: 'Poland',         cur: 'PLN', phone: '+48'  },
  { flag: '🇷🇺', name: 'Russia',         cur: 'RUB', phone: '+7'   },
  { flag: '🇺🇦', name: 'Ukraine',        cur: 'UAH', phone: '+380' },
  { flag: '🇸🇪', name: 'Sweden',         cur: 'SEK', phone: '+46'  },
  { flag: '🇨🇭', name: 'Switzerland',    cur: 'CHF', phone: '+41'  },
  { group: '🌍 Africa' },
  { flag: '🇳🇬', name: 'Nigeria',        cur: 'NGN', phone: '+234' },
  { flag: '🇿🇦', name: 'South Africa',   cur: 'ZAR', phone: '+27'  },
  { flag: '🇪🇬', name: 'Egypt',          cur: 'EGP', phone: '+20'  },
  { flag: '🇰🇪', name: 'Kenya',          cur: 'KES', phone: '+254' },
  { flag: '🇬🇭', name: 'Ghana',          cur: 'GHS', phone: '+233' },
  { group: '🌍 Americas' },
  { flag: '🇨🇦', name: 'Canada',         cur: 'CAD', phone: '+1'   },
  { flag: '🇧🇷', name: 'Brazil',         cur: 'BRL', phone: '+55'  },
  { flag: '🇲🇽', name: 'Mexico',         cur: 'MXN', phone: '+52'  },
  { flag: '🇦🇷', name: 'Argentina',      cur: 'ARS', phone: '+54'  },
  { flag: '🇨🇴', name: 'Colombia',       cur: 'COP', phone: '+57'  },
  { group: '🌍 Oceania' },
  { flag: '🇦🇺', name: 'Australia',      cur: 'AUD', phone: '+61'  },
  { flag: '🇳🇿', name: 'New Zealand',    cur: 'NZD', phone: '+64'  },
];
