export const PLANS = [
  {
    id: 'Mool',
    name: 'Mool',
    price: 'FREE',
    priceSub: '/ forever',
    priceColor: 'var(--green)',
    popular: false,
    features: ['Worldwide ATM', '100 USDT Voucher', '10% Cashback'],
    btnClass: 'outline',
    btnText: 'Apply Free',
    desc: 'FREE forever · 10% cashback on every swipe',
  },
  {
    id: 'Pro',
    name: 'Pro',
    price: '19.99',
    priceSub: 'USDT/mo',
    nameColor: 'var(--bnb)',
    popular: true,
    features: ['Priority Global', '100 USDT Voucher', '10% Cashback', 'VIP Support'],
    btnClass: 'filled',
    btnText: 'Apply Pro',
    desc: '19.99 USDT/mo · 10% cashback on every swipe · VIP support',
  },
  {
    id: 'Premium',
    name: 'Premium',
    price: '49.99',
    priceSub: 'USDT/mo',
    nameColor: 'var(--t2)',
    popular: false,
    features: ['Unlimited Global', '100 USDT Voucher', '10% Cashback'],
    btnClass: 'outline',
    btnText: 'Apply Premium',
    desc: '49.99 USDT/mo · 10% cashback on every swipe · Zero fees',
  },
];
